global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'webserver'
    static_configs:
      - targets: ['localhost:80'] # Use the appropriate port for your webserver

  - job_name: 'mysql'
    static_configs:
      - targets: ['localhost:3306'] # Use the appropriate port for your MySQL